// examples/vue-host/App.vue
<script setup lang="ts">
import { onMounted, onUnmounted } from 'vue'
import { createSupportClient, type SupportClient } from '@nipoto/support-web-sdk'

/**
 * Thin Vue host. Public Web SDK only — no Support app internals.
 */
let client: SupportClient | null = null

onMounted(() => {
  client = createSupportClient({
    origin: 'http://localhost:5173',
    widgetId: 'wid_public_example',
    locale: 'fa-IR',
  })
})

onUnmounted(() => {
  void client?.dispose()
  client = null
})
</script>

<template>
  <main>Vue host — Support UI stays in the iframe.</main>
</template>

// examples/react-host/App.tsx
import { useEffect } from 'react'
import { createSupportClient } from '@nipoto/support-web-sdk'

/**
 * Thin React host. Calls the public Web SDK only — no Vue, Pinia, gateway, or app internals.
 * Token stays out of the URL and Web Storage. setSession is a generation bump; cookie is the credential.
 */
export function App() {
  useEffect(() => {
    const client = createSupportClient({
      origin: 'http://localhost:5173',
      widgetId: 'wid_public_example',
      locale: 'fa-IR',
    })
    void client.ready
    return () => {
      void client.dispose()
    }
  }, [])

  return <main>React host — Support UI stays in the iframe.</main>
}
